### ISSUE TITLE
Willow Auto Correct Encountered an Error 

### ISSUE THREAD

**Issue by guarddog13** [toverainc/willow-autocorrect#5]
I am not sure where to troubleshoot this error. It started yesterday after a reboot of my host. I rebuilt the wac image, I changed from the loopback address to the host address in both wac and wis. I continually get the error Willow Auto Correct Encountered an Error. 

```
2024-02-18T11:27:16.562260428Z 2024-02-18 11:27:16 ERROR    WAC FAILED with Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:16.562288752Z Traceback (most recent call last):
2024-02-18T11:27:16.562293231Z   File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
2024-02-18T11:27:16.562296854Z     return complexjson.loads(self.text, **kwargs)
2024-02-18T11:27:16.562300427Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:16.562303676Z   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
2024-02-18T11:27:16.562307016Z     return _default_decoder.decode(s)
2024-02-18T11:27:16.562310190Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:16.562313452Z   File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
2024-02-18T11:27:16.562316722Z     raise JSONDecodeError("Extra data", s, end)
2024-02-18T11:27:16.562320027Z json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:16.562323282Z 
2024-02-18T11:27:16.562326455Z During handling of the above exception, another exception occurred:
2024-02-18T11:27:16.562329689Z 
2024-02-18T11:27:16.562332828Z Traceback (most recent call last):
2024-02-18T11:27:16.562336034Z   File "/app/wac.py", line 696, in api_post_proxy_handler
2024-02-18T11:27:16.562339359Z     ha_response = ha_response.json()
2024-02-18T11:27:16.562342562Z                   ^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:16.562345793Z   File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
2024-02-18T11:27:16.562349081Z     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-02-18T11:27:16.562352681Z requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:16.562356005Z 2024-02-18 11:27:16 INFO     WAC proxy total time 100.429 ms
2024-02-18T11:27:16.562672440Z [2024-02-18T11:27:16] INFO:     127.0.0.1:36878 - 'POST /api/proxy HTTP/1.1' 200 OK
2024-02-18T11:27:57.034887508Z 2024-02-18 11:27:57 INFO     Processing proxy request from 'willow-f412fae23a18' for command 'Turn off hallway' with distance 2 token match threshold 3 exact match False semantic hybrid with vector distance threshold 0.29 and hybrid threshold 0.85
2024-02-18T11:27:57.034917948Z 2024-02-18 11:27:57 INFO     Trying initial HA intent match 'Turn off hallway'
2024-02-18T11:27:57.129046642Z 2024-02-18 11:27:57 ERROR    WAC FAILED with Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:57.129106212Z Traceback (most recent call last):
2024-02-18T11:27:57.129110637Z   File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
2024-02-18T11:27:57.129114249Z     return complexjson.loads(self.text, **kwargs)
2024-02-18T11:27:57.129130392Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:57.129133455Z   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
2024-02-18T11:27:57.129136640Z     return _default_decoder.decode(s)
2024-02-18T11:27:57.129139749Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:57.129142831Z   File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
2024-02-18T11:27:57.129145989Z     raise JSONDecodeError("Extra data", s, end)
2024-02-18T11:27:57.129149147Z json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:57.129152258Z 
2024-02-18T11:27:57.129155268Z During handling of the above exception, another exception occurred:
2024-02-18T11:27:57.129158367Z 
2024-02-18T11:27:57.129161437Z Traceback (most recent call last):
2024-02-18T11:27:57.129164507Z   File "/app/wac.py", line 696, in api_post_proxy_handler
2024-02-18T11:27:57.129167629Z     ha_response = ha_response.json()
2024-02-18T11:27:57.129170630Z                   ^^^^^^^^^^^^^^^^^^
2024-02-18T11:27:57.129173662Z   File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
2024-02-18T11:27:57.129176982Z     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-02-18T11:27:57.129180043Z requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)
2024-02-18T11:27:57.129183170Z 2024-02-18 11:27:57 INFO     WAC proxy total time 94.32300000000001 ms
2024-02-18T11:27:57.129334399Z [2024-02-18T11:27:57] INFO:     127.0.0.1:33858 - 'POST /api/proxy HTTP/1.1' 200 OK

**Comment by nikito** [comment]
Has your home assistant updated recently as well? They made some changes to their api that can cause this, which we fixed in latest main branch of wac. You may want to pull and rebuild/redeploy it. 🙂

**Comment by guarddog13** [comment]
Yes it updated... but I already pulled and redeployed. It was one of the tests I tried on fixing this too.

**Comment by nikito** [comment]
Not sure what is meant by "changed from loopback address to host address in both wac and wis" l. Where was this change made? Only other place i can think to look is on the HA side to see if it isn't connecting properly

**Comment by guarddog13** [comment]
> Not sure what is meant by "changed from loopback address to host address in both wac and wis" l. Where was this change made? Only other place i can think to look is on the HA side to see if it isn't connecting properly

My WAC and WIS are on the same server. Sometimes the loopback ip (127.0.0.1) seems to fail with docker containers, so I switched back and forth to make sure. It seems that looking at the response that HA might not be connected properly. Not sure where I would troubleshoot this as I changed the Token too to make sure that wasn't the issue.

**Comment by nikito** [comment]
Seems it likely is getting some dirty if reply back from the server that doesn't decode to json as expected, exist probably means something is wrong with the connection. Not sure how to troubleshoot that other than validating connectivity between the systems and ensuring all the configs are properly set in WAC/WAS including the HA token. 🫤

**Comment by guarddog13** [comment]
> Seems it likely is getting some dirty if reply back from the server that doesn't decode to json as expected, exist probably means something is wrong with the connection. Not sure how to troubleshoot that other than validating connectivity between the systems and ensuring all the configs are properly set in WAC/WAS including the HA token. 🫤

It was an issue on the HA side. I had an error in a custom sentence yaml and it was causing HA Assist to break.
